#!/usr/bin/python3

benchmarks = [ 'com.github.yeriomin.dumbphoneassistant_5', 'org.csploit.android', 'com.ilm.sandwich_2.2.4f', 
    'com.kunzisoft.keepass.libre_2.5.0.0beta18', 'dk.jens.backup_0.3.4', 'org.gateshipone.odyssey_30',
    'com.alfray.timeriffic_10905', 'org.decsync.sparss.floss_1.13.4',  'com.github.axet.callrecorder_219', 
    'org.materialos.icons_2.1', 'com.app.Zensuren_1.21', 'name.myigel.fahrplan.eh17_1.33.16', 
    'com.emn8.mobilem8.nativeapp.bk_5.0.10', 'com.genonbeta.TrebleShot_98', 'com.microsoft.office.word_16.0.11425.20132', 
    'org.secuso.privacyfriendlytodolist_2.1',  'com.vonglasow.michael.satstat', 'com.igisw.openmoneybox.3.4.1.8',
    'com.kanedias.vanilla.metadata_5', 'org.secuso.privacyfriendlyweather_6', 'com.adobe.reader_19.2.1.9183', 
    'org.totschnig.myexpenses', 'org.fdroid.fdroid_1008000', 'org.lumicall.android_190', 'nya.miku.wishmaster_54',   
    'org.openpetfoodfacts.scanner_2.9.8', 'bus.chio.wishmaster_1002', 'com.github.axet.bookreader_375', 
]

ben2name = {
    'bus.chio.wishmaster_1002': 'bus.chio.wishmaster',
    'com.adobe.reader_19.2.1.9183': 'com.adobe.reader',
    'com.alfray.timeriffic_10905': 'com.alfray.timeriffic',
    'com.app.Zensuren_1.21': 'com.app.Zensuren',
    'com.emn8.mobilem8.nativeapp.bk_5.0.10': 'com.emn8.mobilem8.nativeapp.bk',
    'com.genonbeta.TrebleShot_98': 'com.genonbeta.TrebleShot',
    'com.github.axet.bookreader_375': 'com.github.axet.bookreader',
    'com.github.axet.callrecorder_219': 'com.github.axet.callrecorder',
    'com.github.yeriomin.dumbphoneassistant_5': 'com.github.yeriomin.dumbphoneassistant',
    'com.igisw.openmoneybox.3.4.1.8': 'com.igisw.openmoneybox',
    'com.ilm.sandwich_2.2.4f': 'com.ilm.sandwich',
    'com.kanedias.vanilla.metadata_5': 'com.kanedias.vanilla.metadata',
    'com.kunzisoft.keepass.libre_2.5.0.0beta18': 'com.kunzisoft.keepass.libre',
    'com.microsoft.office.word_16.0.11425.20132': 'com.microsoft.office.word',
    'com.vonglasow.michael.satstat': 'com.vonglasow.michael.satstat',
    'dk.jens.backup_0.3.4': 'dk.jens.backup',
    'name.myigel.fahrplan.eh17_1.33.16': 'name.myigel.fahrplan.eh17',
    'nya.miku.wishmaster_54': 'nya.miku.wishmaster',
    'org.csploit.android': 'org.csploit.android',
    'org.totschnig.myexpenses': 'org.totschnig.myexpenses',
    'org.decsync.sparss.floss_1.13.4': 'org.decsync.sparss.floss',
    'org.fdroid.fdroid_1008000': 'org.fdroid.fdroid',
    'org.gateshipone.odyssey_30': 'org.gateshipone.odyssey',
    'org.lumicall.android_190': 'org.lumicall.android',
    'org.materialos.icons_2.1': 'org.materialos.icons',
    'org.openpetfoodfacts.scanner_2.9.8': 'org.openpetfoodfacts.scanner',
    'org.secuso.privacyfriendlytodolist_2.1': 'org.secuso.privacyfriendlytodolist',
    'org.secuso.privacyfriendlyweather_6': 'org.secuso.privacyfriendlyweather'
}

ben2version = {
    'bus.chio.wishmaster_1002': '1.0.2',
    'com.adobe.reader_19.2.1.9183': '19.2.1.9183',
    'com.alfray.timeriffic_10905': '1.09.05',
    'com.app.Zensuren_1.21': '1.21',
    'com.emn8.mobilem8.nativeapp.bk_5.0.10': '5.0.10',
    'com.genonbeta.TrebleShot_98': '1.4.2',
    'com.github.axet.bookreader_375': '1.12.14',
    'com.github.axet.callrecorder_219': '1.7.13',
    'com.github.yeriomin.dumbphoneassistant_5': '0.5',
    'com.igisw.openmoneybox.3.4.1.8': '3.4.1.8', # this is also the newer version than the one used in SparseDroid.
    'com.ilm.sandwich_2.2.4f': '2.2.4f',
    'com.kanedias.vanilla.metadata_5': '1.0.4',
    'com.kunzisoft.keepass.libre_2.5.0.0beta18': '2.5.0.0beta18',
    'com.microsoft.office.word_16.0.11425.20132': '16.0.11425.20132',
    'com.vonglasow.michael.satstat': '3.3',
    'dk.jens.backup_0.3.4': '0.3.4',
    'name.myigel.fahrplan.eh17_1.33.16': '1.33.16',
    'nya.miku.wishmaster_54': '1.5.0',
    'org.csploit.android': '1.6.5',
    'org.totschnig.myexpenses': '3.0.1.2',
    'org.decsync.sparss.floss_1.13.4': '1.13.4',
    'org.fdroid.fdroid_1008000': '1.8-alpha0',
    'org.gateshipone.odyssey_30': '1.1.18',
    'org.lumicall.android_190': '1.13.1',
    'org.materialos.icons_2.1': '2.1',
    'org.openpetfoodfacts.scanner_2.9.8': '2.9.8',
    'org.secuso.privacyfriendlytodolist_2.1': '2.1',
    'org.secuso.privacyfriendlyweather_6': '2.1.1'
}